name: CI Minimal Build & Deploy
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Clean cache
        run: npm cache clean --force 
      - name: Remove node_modules
        run: rm -rf node_modules package-lock.json
      - name: Debug
        run: echo "Passei por aqui paizão!"
        
      - name: Install deps
        run: npm install --no-audit --no-fund --prefer-online
        
      - name: Build site
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
